project:
  type: website

website:
  title: "AOMC Model Documentation"
  navbar:
    left:
      - href: about.qmd
        text: "About"
      - href: index.qmd
        text: Home
      - href: input_docs/theory.qmd
        text: Model Theory
      - text: "Input Files"
        menu:
          - href: input_docs/amc_inp.qmd
            text: "amc.inp"
          - href: input_docs/abs_inp.qmd
            text: "abs.inp"
          - href: input_docs/scat_inp.qmd
            text: "scat.inp"
          - href: input_docs/conc_inp.qmd
            text: "conc.inp"
          - href: input_docs/spf_inp.qmd
            text: "spf.qmd"
          - href: input_docs/lambbot_inp.qmd
            text: "lambbot.qmd"
          - href: input_docs/difcol_inp.qmd
            text: "difcol.qmd"
          - href: input_docs/skydist_inp.qmd
            text: "skydist.qmd"
      - href: input_docs/compilation.qmd
        text: Compilation
    right:
      - icon: github
        href: https://github.com/mgimond/aomc
       
format:
   html:
     theme: cosmo  
     toc: true     
     code-fold: true 
     math:
       method: katex